apiVersion: apps/v1
kind: Deployment
metadata:
  name: day4-juhyun-configserver-deployment
  namespace: group1-team3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: day4-juhyun-configserver-app
  template:
    metadata:
      labels:
        app: day4-juhyun-configserver-app
    spec:
      containers:
        - name: day4-juhyun-configserver-con
          image: "k8s-vga-worker1:5000/group1-team3-juhyun-day4-configserver:s14"
          ports:
            - containerPort: 9200
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: day4-juhyun-configserver-service
spec:
  selector:
    app: day4-juhyun-configserver-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9200
