spring:
  config:
    import: "optional:configserver:http://localhost:9200/"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9201/eureka/
info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application Local"
    version: "1.0.0"
